### ISSUE TITLE
Hängen im Loading-screen

### ISSUE THREAD

**Issue by Michel12334** [Achim-Sommer/FiveM-ESX-Template-Server#1]
Moin, onesync ist an im Lagancy mode aber alle esx Sachen + es_extended starten nicht...

Die Console:

================================================================
======== FXServer Starting - 18.6.2023, 15:51:59                
================================================================
[           resources] Scanning resources.
[resources:ItemBilder] Warning: ItemBilder does not have a resource manifest (fxmanifest.lua)
[       resources:SQL] Warning: SQL does not have a resource manifest (fxmanifest.lua)
[           resources] Found 96 resources.
[           resources] 2 warnings were encountered.
[          svadhesive] Authenticating server license key...
[          svadhesive] Server license key authentication succeeded. Welcome!
[ citizen-server-impl] Couldn't find resource sessionmanager.
[    c-scripting-core] Creating script environments for monitor
[      script:monitor] [txAdmin] Resource v6.0.0 threads and commands set up. All Ready.
[           resources] Started resource monitor
[ citizen-server-impl] Couldn't find resource chat.
[ citizen-server-impl] Couldn't find resource spawnmanager.
[ citizen-server-impl] Couldn't find resource sessionmanager.
[ citizen-server-impl] Couldn't find resource hardcap.
[ citizen-server-impl] Couldn't find resource chat-theme-gtao.
[    c-scripting-core] [0mCreating script environments for oxmysql
[           resources] Started resource oxmysql
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[ citizen-server-impl] Couldn't start resource ox_lib.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[ citizen-server-impl] Couldn't start resource es_extended.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource ox_target.
[ citizen-server-impl] Couldn't start resource ox_target.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource ox_inventory.
[    c-resources-core] Resource 'ox_inventory' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[ citizen-server-impl] Couldn't start resource ox_inventory.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource ox_fuel.
[ citizen-server-impl] Couldn't start resource ox_fuel.
[    c-scripting-core] Creating script environments for async
[           resources] Started resource async
[    c-scripting-core] Creating script environments for cron
[           resources] Started resource cron
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[ citizen-server-impl] Couldn't start resource es_extended.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_context.
[ citizen-server-impl] Couldn't start resource esx_context.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_identity.
[ citizen-server-impl] Couldn't start resource esx_identity.
[    c-scripting-core] Creating script environments for esx_loadingscreen
[           resources] Started resource esx_loadingscreen
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_menu_default.
[ citizen-server-impl] Couldn't start resource esx_menu_default.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_menu_dialog.
[ citizen-server-impl] Couldn't start resource esx_menu_dialog.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_menu_list.
[ citizen-server-impl] Couldn't start resource esx_menu_list.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_multicharacter.
[ citizen-server-impl] Couldn't start resource esx_multicharacter.
[    c-scripting-core] Creating script environments for esx_notify
[   script:esx_notify] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[           resources] Started resource esx_notify
[    c-scripting-core] Creating script environments for esx_progressbar
[script:esx_progressb] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[           resources] Started resource esx_progressbar
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_skin.
[ citizen-server-impl] Couldn't start resource esx_skin.
[    c-scripting-core] Creating script environments for esx_textui
[   script:esx_textui] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[           resources] Started resource esx_textui
[           resources] Started resource skinchanger
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_addonaccount.
[ citizen-server-impl] Couldn't start resource esx_addonaccount.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_addoninventory.
[ citizen-server-impl] Couldn't start resource esx_addoninventory.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_banking.
[ citizen-server-impl] Couldn't start resource esx_banking.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_barbershop.
[ citizen-server-impl] Couldn't start resource esx_barbershop.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_basicneeds.
[ citizen-server-impl] Couldn't start resource esx_basicneeds.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_billing.
[ citizen-server-impl] Couldn't start resource esx_billing.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[38;5;163m[    c-resources-core] Could not start dependency es_extended for resource esx_boat.
[ citizen-server-impl] Couldn't start resource esx_boat.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_clotheshop.
[ citizen-server-impl] Couldn't start resource esx_clotheshop.
[    c-scripting-core] Creating script environments for esx_datastore
[script:esx_datastore] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[           resources] Started resource esx_datastore
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_dmvschool.
[ citizen-server-impl] Couldn't start resource esx_dmvschool.
[    c-scripting-core] Creating script environments for esx_garage
[   script:esx_garage] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[   script:esx_garage] SCRIPT ERROR: @esx_garage/server/main.lua:44: attempt to index a nil value (global 'ESX')
[   script:esx_garage] > fn (@esx_garage/server/main.lua:44)
[           resources] Started resource esx_garage
[    c-scripting-core] Creating script environments for esx_license
[  script:esx_license] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[  script:esx_license] SCRIPT ERROR: @esx_license/server/main.lua:134: attempt to index a nil value (global 'ESX')
[  script:esx_license] > fn (@esx_license/server/main.lua:134)
[           resources] Started resource esx_license
[    c-scripting-core] Creating script environments for esx_optionalneeds
[script:esx_optionaln] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[script:esx_optionaln] SCRIPT ERROR: @esx_optionalneeds/server/main.lua:1: attempt to index a nil value (global 'ESX')
[script:esx_optionaln] > fn (@esx_optionalneeds/server/main.lua:1)
[           resources] Started resource esx_optionalneeds
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_property.
[ citizen-server-impl] Couldn't start resource esx_property.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_society.
[ citizen-server-impl] Couldn't start resource esx_society.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_status.
[ citizen-server-impl] Couldn't start resource esx_status.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_ambulancejob.
[ citizen-server-impl] Couldn't start resource esx_ambulancejob.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_joblisting.
[ citizen-server-impl] Couldn't start resource esx_joblisting.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_jobs.
[ citizen-server-impl] Couldn't start resource esx_jobs.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_mechanicjob.
[ citizen-server-impl] Couldn't start resource esx_mechanicjob.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_policejob.
[ citizen-server-impl] Couldn't start resource esx_policejob.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_taxijob.
[ citizen-server-impl] Couldn't start resource esx_taxijob.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_vehicleshop.
[ citizen-server-impl] Couldn't start resource esx_vehicleshop.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource renzu_tuners.
[    c-resources-core] Resource 'renzu_tuners' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[ citizen-server-impl] Couldn't start resource renzu_tuners.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[ citizen-server-impl] Couldn't start resource es_extended.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_context.
[ citizen-server-impl] Couldn't start resource esx_context.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_identity.
[ citizen-server-impl] Couldn't start resource esx_identity.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_menu_default.
[ citizen-server-impl] Couldn't start resource esx_menu_default.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_menu_dialog.
[ citizen-server-impl] Couldn't start resource esx_menu_dialog.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_menu_list.
[ citizen-server-impl] Couldn't start resource esx_menu_list.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_multicharacter.
[ citizen-server-impl] Couldn't start resource esx_multicharacter.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_skin.
[ citizen-server-impl] Couldn't start resource esx_skin.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_addonaccount.
[ citizen-server-impl] Couldn't start resource esx_addonaccount.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_addoninventory.
[ citizen-server-impl] Couldn't start resource esx_addoninventory.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_banking.
[ citizen-server-impl] Couldn't start resource esx_banking.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_barbershop.
[ citizen-server-impl] Couldn't start resource esx_barbershop.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_basicneeds.
[ citizen-server-impl] Couldn't start resource esx_basicneeds.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_billing.
[ citizen-server-impl] Couldn't start resource esx_billing.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_boat.
[ citizen-server-impl] Couldn't start resource esx_boat.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_clotheshop.
[ citizen-server-impl] Couldn't start resource esx_clotheshop.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_dmvschool.
[ citizen-server-impl] Couldn't start resource esx_dmvschool.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_property.
[ citizen-server-impl] Couldn't start resource esx_property.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_society.
[ citizen-server-impl] Couldn't start resource esx_society.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_status.
[ citizen-server-impl] Couldn't start resource esx_status.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_ambulancejob.
[ citizen-server-impl] Couldn't start resource esx_ambulancejob.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_joblisting.
[ citizen-server-impl] Couldn't start resource esx_joblisting.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_jobs.
[ citizen-server-impl] Couldn't start resource esx_jobs.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_mechanicjob.
[ citizen-server-impl] Couldn't start resource esx_mechanicjob.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_policejob.
[ citizen-server-impl] Couldn't start resource esx_policejob.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_taxijob.
[ citizen-server-impl] Couldn't start resource esx_taxijob.[0m
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_vehicleshop.
[ citizen-server-impl] Couldn't start resource esx_vehicleshop.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource renzu_tuners.
[    c-resources-core] Resource 'renzu_tuners' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[ citizen-server-impl] Couldn't start resource renzu_tuners.
[           resources] Started resource bob74_ipl
[38;5;83m[           resources] Started resource iplLoader
[           resources] Started resource utk_ornateprops
[           resources] Started resource banner_anim
[           resources] Started resource verpi_driving_school
[           resources] Started resource verpi_jobcentre
[           resources] Started resource breze_benefactor
[           resources] Started resource smokey_grove
[resources:casinoexte] Asset casinoexterior/hei_ch3_12_casinonew_emmisive.ydr uses 24.0 MiB of physical memory.
[resources:casinoexte] Asset casinoexterior/hei_ch3_12_vw_dlc_casino.ytd uses 16.2 MiB of physical memory.
[           resources] Started resource casinoexterior (2 warnings)
[resources:casinointe] Warning: could not find client_script `client.lua` (defined in __resource.lua:5)
[resources:casinointe] Asset casinointerior/vw_vwint01_vwdlc_vw_casino.ytd uses 25.8 MiB of physical memory.
[           resources] Started resource casinointerior (2 warnings)
[           resources] Started resource cassino_props
[           resources] Started resource hospitalsandy
[           resources] Started resource pd_sandy
[           resources] Started resource prompt_paleto_clinic
[  resources:paletopd] Warning: could not find file `interiorproxies.meta` (defined in __resource.lua:4)
[           resources] Started resource paletopd (1 warning)
[    c-scripting-core] Creating script environments for mosleynutt
[resources:mosleynutt] Warning: could not find client_script `client/props.lua` (defined in fxmanifest.lua:8)
[resources:mosleynutt] Asset mosleynutt/lock_texts.ytd uses 72.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (such as models not loading/rendering).[0m
[resources:mosleynutt] Asset mosleynutt/lockers.ydr uses 132.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (such as models not loading/rendering).
[resources:mosleynutt] Asset mosleynutt/mos_office_bar.ydr uses 36.5 MiB of physical memory.
[resources:mosleynutt] Asset mosleynutt/nutt_mos_bath_details.ydr uses 80.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (such as models not loading/rendering).
[resources:mosleynutt] [91mAsset mosleynutt/nutt_mosley_fd.ydr uses 80.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (such as models not loading/rendering).
[resources:mosleynutt] Asset mosleynutt/nutt_mosley_textures.ytd uses 44.0 MiB of physical memory.
[           resources] Started resource mosleynutt (7 warnings)
[           resources] Started resource Meetingroomprison
[           resources] Started resource Prisoncanteen
[resources:Prisonmain] Asset Prisonmainblock/desertos_prison.ytd uses 30.5 MiB of physical memory.
[           resources] Started resource Prisonmainblock (1 warning)
[resources:screenshot] Warning: could not find client_script `dist/client.js` (defined in fxmanifest.lua:4)[0m
[resources:screenshot] Warning: could not find server_script `dist/server.js` (defined in fxmanifest.lua:5)
[resources:screenshot] Warning: could not find file `dist/ui.html` (defined in fxmanifest.lua:7)
[           resources] Started resource screenshot-basic (3 warnings)
[    c-resources-core] Resource 'pma-voice' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[ citizen-server-impl] Couldn't start resource pma-voice.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx-npwd.
[ citizen-server-impl] Couldn't start resource esx-npwd.
[    c-resources-core] Resource 'pma-voice' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency pma-voice for resource npwd.
[ citizen-server-impl] Couldn't start resource npwd.
[    c-scripting-core] Creating script environments for DiamondBlackjack
[script:DiamondBlackj] SCRIPT ERROR: @DiamondBlackjack/sv_blackjack.lua:26: No such export getSharedObject in resource es_extended
[resources:DiamondBla] Warning: could not find client_script `src/RMenu.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/RageUI.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/Menu.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/MenuController.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/components/*.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/elements/*.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/items/*.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/panels/*.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/panels/*.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Warning: could not find client_script `src/menu/windows/*.lua` (defined in fxmanifest.lua:7)
[resources:DiamondBla] Asset DiamondBlackjack/s_f_y_casino_01.ytd uses 20.0 MiB of physical memory.
[resources:DiamondBla] Asset DiamondBlackjack/s_m_y_casino_01.ytd uses 20.2 MiB of physical memory.
[           resources] Started resource DiamondBlackjack (12 warnings)
[    c-scripting-core] Creating script environments for EngineToggle
[           resources] Started resource EngineToggle
[    c-scripting-core] Creating script environments for PauseMenu
[           resources] Started resource PauseMenu
[           resources] Started resource Peds
[    c-scripting-core] Creating script environments for anims
[           resources] Started resource anims
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource b1g_notify.
[ citizen-server-impl] Couldn't start resource b1g_notify.
[           resources] Started resource chCasinoWall
[    c-scripting-core] Creating script environments for dr-scratching
[script:dr-scratching] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[script:dr-scratching] SCRIPT ERROR: @dr-scratching/server/s_main.lua:11: attempt to index a nil value (global 'ESX')
[script:dr-scratching] > fn (@dr-scratching/server/s_main.lua:11)
[           resources] Started resource dr-scratching
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource dx_hud.
[ citizen-server-impl] Couldn't start resource dx_hud.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource esx_advancedholdup.
[ citizen-server-impl] Couldn't start resource esx_advancedholdup.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource ox_inventory.
[    c-resources-core] Resource 'ox_inventory' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_inventory for resource fuksus-shops.
[ citizen-server-impl] Couldn't start resource fuksus-shops.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource hyon_stealfuel.
[ citizen-server-impl] [0mCouldn't start resource hyon_stealfuel.
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource id_playtimereward.
[    c-resources-core] Resource 'id_playtimereward' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[ citizen-server-impl] Couldn't start resource id_playtimereward.
[    c-scripting-core] Creating script environments for jsfour-idcard
[script:jsfour-idcard] SCRIPT ERROR: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[           resources] Started resource jsfour-idcard
[    c-scripting-core] Creating script environments for k5_documents
[ script:k5_documents] [31mERROR: This script only supports ESX and QBCore frameworks, but non of these are present. Unfortunatelly, you cannot use this script.
[           resources] [0mStarted resource k5_documents
[           resources] Started resource k5_notify
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource krz_personalmenu.
[ citizen-server-impl] Couldn't start resource krz_personalmenu.
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource ox_doorlock.
[ citizen-server-impl] Couldn't start resource ox_doorlock.
[    c-scripting-core] Creating script environments for pickle_prisons
[script:pickle_prison] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:90: ox_lib should be started before this resource.
[script:pickle_prison] > fn (@ox_lib/init.lua:13)
[script:pickle_prison] You are not using a supported framework, it will be required to make edits to the bridge files.
[script:pickle_prison] SCRIPT ERROR: @pickle_prisons/modules/activities/server.lua:44: attempt to call a nil value (global 'RegisterCallback')
[script:pickle_prison] > fn (@pickle_prisons/modules/activities/server.lua:44)
[script:pickle_prison] SCRIPT ERROR: @pickle_prisons/modules/prison/server.lua:127: attempt to call a nil value (global 'RegisterCallback')
[script:pickle_prison] > fn (@pickle_prisons/modules/prison/server.lua:127)
[           resources] Started resource pickle_prisons
[    c-resources-core] Could not find dependency spawnmanager for resource es_extended.
[    c-resources-core] Could not start dependency es_extended for resource program-casino.
[ citizen-server-impl] Couldn't start resource program-casino.
[    c-resources-core] Could not find dependency chat for resource s1lent_keybinds.
[ citizen-server-impl] Couldn't start resource s1lent_keybinds.
[    c-scripting-core] Creating script environments for sloty
[        script:sloty] [91mSCRIPT ERROR: @sloty/server.lua:1: No such export getSharedObject in resource es_extended
[           resources] Started resource sloty
[    c-scripting-core] Creating script environments for uniq-playtime
[script:uniq-playtime] SCRIPT ERROR: citizen:/scripting/lua/scheduler.lua:90: ox_lib should be started before this resource.
[script:uniq-playtime] > fn (@ox_lib/init.lua:13)
[script:uniq-playtime] SCRIPT ERROR: @uniq-playtime/server.lua:29: attempt to index a nil value (global 'cache')
[script:uniq-playtime] > handler (@uniq-playtime/server.lua:29)
[           resources] Started resource uniq-playtime
[    c-resources-core] Resource 'ox_lib' can't run:
[    c-resources-core]   1. onesync: OneSync needs to be enabled
[    c-resources-core] Could not start dependency ox_lib for resource wasabi_fishing.
[ citizen-server-impl] Couldn't start resource wasabi_fishing.
[ citizen-server-impl] Couldn't find resource esx_police_cad.
[ citizen-server-impl] Couldn't find resource doge_store.
[ citizen-server-impl] Couldn't find resource esx_drugs.
[ citizen-server-impl] Couldn't find resource HeliCam.
[ citizen-server-impl] Couldn't find resource main_menu.
[ citizen-server-impl] Couldn't find resource as_roulette.
[ citizen-server-impl] [0mCouldn't find resource luckywheel.
[ citizen-server-impl] Couldn't find resource msk_simcard.
[ citizen-server-impl] Could not open zap96x96.png for reading.
[      script:oxmysql] Database server connection established!
[        script:anims] Anims are updated!
[script:uniq-playtime] SCRIPT ERROR: @uniq-playtime/server.lua:79: bad argument #2 to 'gsub' (string/function/table expected, got nil)
[script:uniq-playtime] > fn (@uniq-playtime/server.lua:79)
[script:esx_datastore] SCRIPT ERROR: @esx_datastore/server/main.lua:5: esx_datastore was unable to execute a query!
[script:esx_datastore] Table 'essentialmode.datastore_data' doesn't exist
[script:esx_datastore] SELECT * FROM datastore_data LEFT JOIN datastore ON datastore_data.name = datastore.name UNION SELECT * FROM datastore_data RIGHT JOIN datastore ON datastore_data.name = datastore.name []
[script:esx_datastore] [0m> handler (@esx_datastore/server/main.lua:5)
[script:esx_datastore] > <unknown> (@oxmysql/dist/build.js:21832)
[script:esx_datastore] > processTicksAndRejections (node:internal/process/task_queues:96)
[script:dr-scratching] [dr-scratching] [SUCCESS] Completely up-to-date!
(node:24276) UnhandledPromiseRejectionWarning: Error: esx_license was unable to execute a query!
Table 'essentialmode.licenses' doesn't exist
SELECT type, label FROM licenses []
    at @oxmysql/dist/build.js:21833:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `FXServer --trace-warnings ...` to show where the warning was created)
(node:24276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[      script:oxmysql] An update is available for oxmysql (current version: 2.6.0)
[      script:oxmysql] https://github.com/overextended/oxmysql/releases/tag/v2.7.0
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: https://michel52005-my987q.users.cfx.re/
[ citizen-server-impl] -- [server notice: hostname_rework]
[ citizen-server-impl] You don't have sv_projectName/sv_projectDesc set.
[ citizen-server-impl] These variables augment sv_hostname and fix your server name being cut off in the server list.
[ citizen-server-impl] Use `sets sv_projectName ..` and `sets sv_projectDesc ..` to set them.
[ citizen-server-impl]

**Comment by Achim-Sommer** [comment]
Du musst auch OneSync anmachen.
set onesync on - in der server.cfg


Was hast du für einen Server? Gameserver, vServer, Rootserver? Windows/ Linux?

**Comment by Achim-Sommer** [comment]
Außerdem fehlen dir folgende Sachen.

[ citizen-server-impl] Couldn't find resource spawnmanager.
[ citizen-server-impl] Couldn't find resource sessionmanager.
[ citizen-server-impl] Couldn't find resource hardcap.


Die kommen nicht vom Template Server sondern sind Grundressourcen von einem FiveM Server.

**Comment by Michel12334** [comment]
Guten Morgen,
Ich habe einen VServer. 
Und onesync ist auch in der cfg aktiviert worden..
Nach den drei Ressourcen gucken ich später mal, ob die helfen :)

**Comment by Achim-Sommer** [comment]
Bei einem vServer musst du vorher erstmal einen normalen cleanen dafault CFX Server drauf machen. Der Template Server ist kein kompletter FiveM Server. Der Template Server kommt auf einen FiveM Server drauf. Dementsprechend sind die Base Sachen von einem FiveM Server nicht im Template Server drin.

Das muss in der server.cfg stehen für OneSync
set onesync on 

Steht in der beiliegenden server.cfg in Zeile 15.

Soweit ich weiß brauch man bei einem vServer oder bei über 48 Slots die FiveM Element Club Argentum Mitgliedschaft um OneSync zu nutzen.

Bei einem Gameserver bei Zap-Hosting mit bis zu 48 Slots brauch man das nicht.

Ohne OneSync funktioniert ESX Legacy nicht.

**Comment by Achim-Sommer** [comment]
Ich habe in der Readme jetzt die Installationsanleitung ergänzt.

# Installationsanleitung:
## Die Anleitung ist für einen neuen FiveM Server
### Wichtig! Hast du einen TxAdmin Server musst du bei der Einrichtung von TxAdmin, Popular Template auswählen und dann Default CFX.

- Bei einem vServer oder Rootserver musst du erstmal einen Cleanen FiveM Server auf diesen installieren.
- Bei einem vServer oder Rootserver brauchst du die FiveM Element Club Argentum Mitgliedschaft um OneSync zu nutzen.
- Bei einem Gameserver von Zap-hosting brauchst du die FiveM Element Club Argentum Mitgleidschaft erst bei über 48 Slots.


1.
Füge folgende Ordner in deinen resources Ordner ein:
- [core]
- [esxaddon]
- [esxjobs]
- [maps]
- [extras]
- [ox]
- [phone]
- [templateserveraddon]

2.
Füge folgende Dateien in deinen server-data Ordner ein:
- inventory.cfg
- maps.cfg
- phone.cfg
- server.cfg

3.
Trage deine MySql Datenbank Verbidung in die server.cfg
- siehe Zeile 16

4.
Trage deine SteamID64(hex) in die server.cfg um Admin zu werden:
- siehe Zeile 68

5.
Trage deinen steam_webApiKey in die server.cfg ein
- siehe Zeile 74
- https://forum.achimsommer.com/home/lexicon/entry/13-fivem-server-steam-api-key-fivem-steam-wird-nicht-erkann/

6.
Importiere die server.sql aus dem [SQL] Ordner per phpmyadmin in deine Datenbank

7.
Hol dir das Support Paket oder das Support Paket mit Addon wenn du möchtest, um das Projekt zu unterstüzen.
- https://shop.achimsommer.com/package/5708271
- https://shop.achimsommer.com/package/5708276
