### ISSUE TITLE
Bitte Update! | GetSharedObject ist veraltet. und andere scripts gehen auch nicht / nicht zu gebrauchen

### ISSUE THREAD

**Issue by justinsanjp** [Achim-Sommer/FiveM-ESX-Template-Server#10]
[fxserver_1728317944.log](https://github.com/user-attachments/files/17281657/fxserver_1728317944.log)

Siehe log

**Comment by Achim-Sommer** [comment]
Anwenderfehler. Der Server läuft. Version läuft 1zu1 so auf einen Txadmin Serveru nd auf einen stock FiveM Server.. 
Der Fehler liegt an deiner Fehlerhaften Installation. Bitte keine weiten Issues aufgrund eines User Fehlers öffnen... danke

[                 cmd] No such config file: maps.cfg
[                 cmd] No such config file: phone.cfg
[                 cmd] No such config file: iventroy.cfg
[ citizen-server-impl] Couldn't find resource mapmanager.
[ citizen-server-impl] Couldn't find resource chat.
[ citizen-server-impl] Couldn't find resource spawnmanager.
[ citizen-server-impl] Couldn't find resource sessionmanager.
[ citizen-server-impl] Couldn't find resource hardcap.

**[ citizen-server-impl] Couldn't find resource es_extended. !!!!!!!!!!!!!!!!!!!!**

Und noch vieles mehr. Instaltionsfehler von dir, außerdem sind viele sachen drauf die gar nicht vom Template server kommen. Wie es in der Anleitung steht muss der Server clean sein für die Installation vom Template Server. Also ein Default CFX Server ohne extra Sachen drauf

**Comment by justinsanjp** [comment]
ich habe direkt das repo gezogen und resources in den resources ordner verschoben, ich habe alles aus der cfg genommen die bei gelegt war. es ist alles aus diesem repo. keine extra skripts, ich kann dies gerne mit video beweis wiederholen

**Comment by justinsanjp** [comment]
es_extendet ist mit drauf, startet aber nicht wie viele andere scripts aus diesem repo.

**Comment by Achim-Sommer** [comment]
Wie gesagt Anwenderfehler, habe die Version 1.4 auf zwei Server frisch installiert ohne Probleme. Dir fehlen Teilweise Standardsachen auch von einem Default CFX Server die gar nicht vom Template kommen. Und das andere Sachen drauf sind kannst du aus dem Serverlog entnehmen. 

Du hast es falsch installiert.

**Comment by justinsanjp** [comment]
Es ist kein anwender fehler. egal wie oft ich es versuche, es passiert das selbe, selbst wenn ich meine custom scripts entferne. ich füge die daten der mysql daten bank hinzu, füge die scripts in den resource ordner, habe es auf meinem main linux server und auf meinem lokalen (veralteten) windows server getestet. 

Koregire mich, wenn ich falsch liege, oder etwas falsches getan habe, aber in meinen augen habe ich alles richtig gemacht. und dieses template ist einfach defekt / zu alt. da manche der scripts die hier sind, zu alt sind und immernoch GetsharedObject verwenden.
Was ich getan habe:

- Ordner Work erstellt
- im Ordner Work via wget das repo heruntergeladen
- es mit unzip entpackt.
- scripts in /home/fivem/server/txdata/server/resources verschoben
- das start vorgehen aus der beigelegten server.cfg rauskopiert und in meine eingefügt.
- datein wie inventory.cfg ins stamm verzeichniss wo die server.cfg ist getan.
- sql in die daten bank eingefügt. (wird nicht im video gezeigt, währe zu hohes risiko.)
Server neugestartet

**Comment by justinsanjp** [comment]
Fehler gefunden |endschuldige die störeung, schönen abend noch.
