### ISSUE TITLE
native(0x6AE51D4B): native 0x6AE51D4B isn't supported

### ISSUE THREAD

**Issue by Protschko** [Achim-Sommer/FiveM-ESX-Template-Server#4]
Moin, ich setze den Server auf, habe Default Server erstellt. Gehe die Anleitung schritt für schritt durch. Mache nichts anders.
Es geht aber trz nichts.
Hier ein Ausschnitt aus meinen txAdmin report.

LG

[ citizen-server-impl] Started resource pd_sandy
[ citizen-server-impl] Started resource prompt_paleto_clinic
[ citizen-server-impl] Started resource paletopd
[    c-scripting-core] Creating script environments for mosleynutt
[ citizen-server-impl] Asset mosleynutt/lock_texts.ytd uses 72.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset mosleynutt/lock_texts.ytd uses 72.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset mosleynutt/nutt_mosley_textures.ytd uses 44.0 MiB of physical memory.
[ citizen-server-impl] Asset mosleynutt/nutt_mosley_textures.ytd uses 44.0 MiB of physical memory.
[ citizen-server-impl] Asset mosleynutt/mos_office_bar.ydr uses 36.5 MiB of physical memory.
[ citizen-server-impl] Asset mosleynutt/mos_office_bar.ydr uses 36.5 MiB of physical memory.
[ citizen-server-impl] Asset mosleynutt/nutt_mosley_fd.ydr uses 80.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset mosleynutt/nutt_mosley_fd.ydr uses 80.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset mosleynutt/lockers.ydr uses 132.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset mosleynutt/lockers.ydr uses 132.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset mosleynutt/nutt_mos_bath_details.ydr uses 80.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Asset mosleynutt/nutt_mos_bath_details.ydr uses 80.0 MiB of physical memory. Oversized assets can and WILL lead to streaming issues (models not loading/rendering, commonly known as 'texture loss', 'city bug' or 'streaming isn't great').
[ citizen-server-impl] Started resource mosleynutt
[ citizen-server-impl] Started resource Meetingroomprison
[ citizen-server-impl] Started resource Prisoncanteen
[ citizen-server-impl] Asset Prisonmainblock/desertos_prison.ytd uses 30.5 MiB of physical memory.
[ citizen-server-impl] Asset Prisonmainblock/desertos_prison.ytd uses 30.5 MiB of physical memory.
[ citizen-server-impl] Started resource Prisonmainblock
[ citizen-server-impl] Running build tasks on resource screenshot-basic - it'll restart once completed.
[ citizen-server-impl] Couldn't start resource screenshot-basic.
[    c-scripting-core] Creating script environments for pma-voice
[ citizen-server-impl] Started resource pma-voice
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource esx-npwd.
[ citizen-server-impl] Couldn't start resource esx-npwd.
[ citizen-server-impl] Running build tasks on resource screenshot-basic - it'll restart once completed.
[    c-resources-core] Could not start dependency screenshot-basic for resource npwd.
[ citizen-server-impl] Couldn't start resource npwd.
[                 cmd] No such config file: iventroy.cfg
[    c-scripting-core] Creating script environments for 5p_pilotjob
[  script:5p_pilotjob] Error loading script @es_extended/imports.lua in resource 5p_pilotjob: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[  script:5p_pilotjob] stack traceback:
[  script:5p_pilotjob] 	[C]: in function 'error'
[  script:5p_pilotjob] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod 'index'
[  script:5p_pilotjob] 	@es_extended/imports.lua:1: in main chunk
[    c-scripting-core] Failed to load script @es_extended/imports.lua.
[ citizen-server-impl] Started resource 5p_pilotjob
[ citizen-server-impl] Started resource Billboard-Medical-Center
[    c-scripting-core] Creating script environments for DiamondBlackjack
[script:DiamondBlackj] Error loading script sv_blackjack.lua in resource DiamondBlackjack: @DiamondBlackjack/sv_blackjack.lua:26: No such export getSharedObject in resource es_extended
[script:DiamondBlackj] stack traceback:
[script:DiamondBlackj] 	[C]: in function 'error'
[script:DiamondBlackj] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod '__index'
[script:DiamondBlackj] 	@DiamondBlackjack/sv_blackjack.lua:26: in main chunk
[    c-scripting-core] Failed to load script sv_blackjack.lua.
[ citizen-server-impl] Asset DiamondBlackjack/s_f_y_casino_01.ytd uses 20.0 MiB of physical memory.
[ citizen-server-impl] Asset DiamondBlackjack/s_f_y_casino_01.ytd uses 20.0 MiB of physical memory.
[ citizen-server-impl] Asset DiamondBlackjack/s_m_y_casino_01.ytd uses 20.2 MiB of physical memory.
[ citizen-server-impl] Asset DiamondBlackjack/s_m_y_casino_01.ytd uses 20.2 MiB of physical memory.
[ citizen-server-impl] Started resource DiamondBlackjack
> sv_maxclients 10 ##ZAP-Hosting: please don't modify
[    c-scripting-core] Creating script environments for EngineToggle
[ citizen-server-impl] Started resource EngineToggle
[    c-scripting-core] Creating script environments for PauseMenu
[ citizen-server-impl] Started resource PauseMenu
[ citizen-server-impl] Started resource Peds
[    c-scripting-core] Creating script environments for anims
[ citizen-server-impl] Started resource anims
[    c-scripting-core] Creating script environments for autowalk
[ citizen-server-impl] Started resource autowalk
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource b1g_notify.
[ citizen-server-impl] Couldn't start resource b1g_notify.
[ citizen-server-impl] Started resource chCasinoWall
[ citizen-server-impl] Started resource datacrack
[    c-scripting-core] Creating script environments for dr-scratching
[script:dr-scratching] Error loading script @es_extended/imports.lua in resource dr-scratching: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[script:dr-scratching] stack traceback:
[script:dr-scratching] 	[C]: in function 'error'
[script:dr-scratching] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod 'index'
[script:dr-scratching] 	@es_extended/imports.lua:1: in main chunk
[    c-scripting-core] Failed to load script @es_extended/imports.lua.
[script:dr-scratching] Error loading script server/s_main.lua in resource dr-scratching: @dr-scratching/server/s_main.lua:11: attempt to index a nil value (global 'ESX')
[script:dr-scratching] stack traceback:
[script:dr-scratching] 	@dr-scratching/server/s_main.lua:11: in main chunk
[    c-scripting-core] Failed to load script server/s_main.lua.
[ citizen-server-impl] Started resource dr-scratching
[    c-scripting-core] Creating script environments for dx_hud
[ citizen-server-impl] Started resource dx_hud
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource epyi_rpradio.
[ citizen-server-impl] Couldn't start resource epyi_rpradio.
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource esx_advancedholdup.
[ citizen-server-impl] Couldn't start resource esx_advancedholdup.
[    c-scripting-core] Creating script environments for fivem_pets
[   script:fivem_pets] Error loading script server/main.lua in resource fivem_pets: @fivem_pets/server/main.lua:1: No such export getSharedObject in resource es_extended
[   script:fivem_pets] stack traceback:
[   script:fivem_pets] 	[C]: in function 'error'
[   script:fivem_pets] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod '__index'
[   script:fivem_pets] 	@fivem_pets/server/main.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource fivem_pets
[    c-resources-core] Resource 'ox_inventory' can't run:
[    c-resources-core]   1. server needs to be 6116 or higher
[    c-resources-core] Could not start dependency ox_inventory for resource fuksus-shops.
[ citizen-server-impl] Couldn't start resource fuksus-shops.
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource hyon_stealfuel.
[ citizen-server-impl] Couldn't start resource hyon_stealfuel.
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource id_playtimereward.
[ citizen-server-impl] Couldn't start resource id_playtimereward.
[ citizen-server-impl] Started resource inventory_support
[    c-scripting-core] Creating script environments for jsfour-idcard
[script:jsfour-idcard] Error loading script @es_extended/imports.lua in resource jsfour-idcard: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[script:jsfour-idcard] stack traceback:
[script:jsfour-idcard] 	[C]: in function 'error'
[script:jsfour-idcard] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod '__index'
[script:jsfour-idcard] 	@es_extended/imports.lua:1: in main chunk
[    c-scripting-core] Failed to load script @es_extended/imports.lua.
[ citizen-server-impl] Started resource jsfour-idcard
[    c-scripting-core] Creating script environments for k5_documents
[ script:k5_documents] ERROR: This script only supports ESX and QBCore frameworks, but non of these are present. Unfortunatelly, you cannot use this script.
[ citizen-server-impl] Started resource k5_documents
[ citizen-server-impl] Started resource k5_notify
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource krz_personalmenu.
[ citizen-server-impl] Couldn't start resource krz_personalmenu.
[    c-scripting-core] Creating script environments for lation_mining
[script:lation_mining] Error loading script @es_extended/imports.lua in resource lation_mining: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[script:lation_mining] stack traceback:
[script:lation_mining] 	[C]: in function 'error'
[script:lation_mining] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod 'index'
[script:lation_mining] 	@es_extended/imports.lua:1: in main chunk
[    c-scripting-core] Failed to load script @es_extended/imports.lua.
[ citizen-server-impl] Started resource lation_mining
[    c-scripting-core] Creating script environments for xsound
[ citizen-server-impl] Started resource xsound
[    c-scripting-core] Creating script environments for nass_carplay
[ citizen-server-impl] Started resource nass_carplay
[    c-scripting-core] Creating script environments for ox_doorlock
[ citizen-server-impl] Started resource ox_doorlock
[    c-scripting-core] Creating script environments for pickle_prisons
[script:pickle_prison] You are not using a supported framework, it will be required to make edits to the bridge files.
[script:pickle_prison] Error loading script modules/activities/server.lua in resource pickle_prisons: @pickle_prisons/modules/activities/server.lua:44: attempt to call a nil value (global 'RegisterCallback')
[script:pickle_prison] stack traceback:
[script:pickle_prison] 	@pickle_prisons/modules/activities/server.lua:44: in main chunk
[    c-scripting-core] Failed to load script modules/activities/server.lua.
[script:pickle_prison] Error loading script modules/prison/server.lua in resource pickle_prisons: @pickle_prisons/modules/prison/server.lua:127: attempt to call a nil value (global 'RegisterCallback')
[script:pickle_prison] stack traceback:
[script:pickle_prison] 	@pickle_prisons/modules/prison/server.lua:127: in main chunk
[    c-scripting-core] Failed to load script modules/prison/server.lua.
[ citizen-server-impl] Started resource pickle_prisons
[ citizen-server-impl] Started resource postal_map
[    c-resources-core] Resource 'es_extended' can't run:
[    c-resources-core]   1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported
[    c-resources-core] Could not start dependency es_extended for resource program-casino.
[ citizen-server-impl] Couldn't start resource program-casino.
[ citizen-server-impl] Started resource s1lent_keybinds
[    c-scripting-core] Creating script environments for sloty
[        script:sloty] Error loading script server.lua in resource sloty: @sloty/server.lua:1: No such export getSharedObject in resource es_extended
[        script:sloty] stack traceback:
[        script:sloty] 	[C]: in function 'error'
[        script:sloty] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod '__index'
[        script:sloty] 	@sloty/server.lua:1: in main chunk
[    c-scripting-core] Failed to load script server.lua.
[ citizen-server-impl] Started resource sloty
[    c-scripting-core] Creating script environments for uniq-playtime
[ citizen-server-impl] Started resource uniq-playtime
[    c-scripting-core] Creating script environments for wasabi_fishing
[script:wasabi_fishin] Error loading script server/server.lua in resource wasabi_fishing: @wasabi_fishing/server/server.lua:84: attempt to call a nil value (global 'RegisterUsableItem')
[script:wasabi_fishin] stack traceback:
[script:wasabi_fishin] 	@wasabi_fishing/server/server.lua:84: in main chunk
[    c-scripting-core] Failed to load script server/server.lua.
[ citizen-server-impl] Started resource wasabi_fishing
[    c-scripting-core] Creating script environments for ws_headlights
[script:ws_headlights] Error loading script @es_extended/imports.lua in resource ws_headlights: @es_extended/imports.lua:1: No such export getSharedObject in resource es_extended
[script:ws_headlights] stack traceback:
[script:ws_headlights] 	[C]: in function 'error'
[script:ws_headlights] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod 'index'
[script:ws_headlights] 	@es_extended/imports.lua:1: in main chunk
[    c-scripting-core] Failed to load script @es_extended/imports.lua.
[script:ws_headlights] Error loading script server/main.lua in resource ws_headlights: @ws_headlights/server/main.lua:1: No such export getSharedObject in resource es_extended
[script:ws_headlights] stack traceback:
[script:ws_headlights] 	[C]: in function 'error'
[script:ws_headlights] 	citizen:/scripting/lua/scheduler.lua:878: in metamethod 'index'
[script:ws_headlights] 	@ws_headlights/server/main.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[ citizen-server-impl] Started resource ws_headlights
[    c-scripting-core] Creating script environments for baseevents
[ citizen-server-impl] Started resource baseevents
[    c-scripting-core] Creating script environments for rconlog
[ citizen-server-impl] Started resource rconlog
[    c-scripting-core] Creating script environments for runcode
[ citizen-server-impl] Started resource runcode
[ citizen-server-impl] Running build tasks on resource sessionmanager-rdr3 - it'll restart once completed.
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[ citizen-server-impl] Couldn't start resource sessionmanager-rdr3.
[ citizen-server-impl] Started resource basic-gamemode
[ citizen-server-impl] Started resource fivem-map-hipster
[ citizen-server-impl] Started resource fivem-map-skater
[           resources] Warning: Resource redm-map-one does not support the current game (gta5).
[ citizen-server-impl] Couldn't start resource redm-map-one.
[    c-scripting-core] Creating script environments for money
[ citizen-server-impl] Started resource money
[    c-scripting-core] Creating script environments for mapmanager
[ citizen-server-impl] Started resource mapmanager
[    c-scripting-core] Creating script environments for money-fountain
[ citizen-server-impl] Started resource money-fountain
[ citizen-server-impl] Started resource money-fountain-example-map
[    c-scripting-core] Creating script environments for ped-money-drops
[ citizen-server-impl] Started resource ped-money-drops
[    c-scripting-core] Creating script environments for player-data
[ citizen-server-impl] Started resource player-data
[    c-scripting-core] Creating script environments for playernames
[ citizen-server-impl] Started resource playernames
[ citizen-server-impl] Running build tasks on resource sessionmanager-rdr3 - it'll restart once completed.
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[ citizen-server-impl] Couldn't start resource sessionmanager-rdr3.
[ citizen-server-impl] Could not open zap96x96.png for reading.
> sv_maxclients 10 ##ZAP-Hosting: please don't modify
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [1/4] Resolving packages...
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] Error: [yarn]	warning Waiting for the other yarn instance to finish (pid undefined, inside undefined)
[        script:anims] Anims are updated!
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[      script:monitor] [txAdminClient] Threads and commands set up. All Ready.
[script:uniq-playtime] SCRIPT ERROR: @uniq-playtime/server.lua:79: bad argument #2 to 'gsub' (string/function/table expected, got nil)
[script:uniq-playtime] > fn (@uniq-playtime/server.lua:79)
[      script:oxmysql] Database server connection established!
[         script:yarn] [yarn]	[2/4] Fetching packages...
[script:dr-scratching] [dr-scratching] [SUCCESS] Completely up-to-date!
[      script:oxmysql] An update is available for oxmysql (current version: 2.6.0)
[      script:oxmysql] https://github.com/overextended/oxmysql/releases/tag/v2.7.2
[ script:renzu_tuners] SQL INSTALL SUCCESSFULLY, dont forget to install the items. /install/ folder 
[  script:esx_license] SCRIPT ERROR: @esx_license/server/main.lua:10: attempt to index a nil value (global 'ESX')
[  script:esx_license] > cb (@esx_license/server/main.lua:10)
[  script:esx_license] > fn (@oxmysql/lib/MySQL.lua:19)
[  script:esx_license] > <unknown> (@oxmysql/dist/build.js:21810)
[  script:esx_license] > processTicksAndRejections (node:internal/process/task_queues:96)
[       script:ox_lib] An update is available for ox_lib (current version: 3.5.0)
[       script:ox_lib] https://github.com/overextended/ox_lib/releases/tag/v3.6.2
[ citizen-server-impl]         fff                          
[ citizen-server-impl]   cccc ff   xx  xx     rr rr    eee  
[ citizen-server-impl] cc     ffff   xx       rrr  r ee   e 
[ citizen-server-impl] cc     ff     xx   ... rr     eeeee  
[ citizen-server-impl]  ccccc ff   xx  xx ... rr      eeeee 
[ citizen-server-impl]                                      
[ citizen-server-impl] Authenticated with cfx.re Nucleus: https://zap-hosting-qj9ojv.users.cfx.re/
[       script:ox_lib] An update is available for ox_doorlock (current version: 1.12.0)
[       script:ox_lib] https://github.com/overextended/ox_doorlock/releases/tag/v1.12.2
[       script:ox_lib] An update is available for ox_target (current version: 1.9.0)
[       script:ox_lib] https://github.com/overextended/ox_target/releases/tag/v1.10.2
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[script:wasabi_fishin] [WARNING] wasabi_fishing is NOT up to date!
[script:wasabi_fishin] [WARNING] Your Version: 2.0.6
[script:wasabi_fishin] [WARNING] Latest Version: 2.0.7
[script:wasabi_fishin] [WARNING] Get the latest Version from: https://github.com/wasabirobby/wasabi_fishing/releases/tag/2.0.7
[script:wasabi_fishin] [WARNING] Changelog:
[script:wasabi_fishin] - Renamed events in bridge directory as they conflict with users utilizing resource `wasabi_bridge`
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[         script:yarn] [yarn]	info fsevents@2.3.1: The platform "linux" is incompatible with this module.
[         script:yarn] [yarn]	info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[         script:yarn] [yarn]	info fsevents@1.2.13: The platform "linux" is incompatible with this module.
[         script:yarn] [yarn]	info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[         script:yarn] [yarn]	[3/4] Linking dependencies...
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[         script:yarn] yarn is currently busy: we are waiting to compile sessionmanager-rdr3
[         script:yarn] [yarn]	[4/4] Building fresh packages...
[         script:yarn] Error: [yarn]	warning Ignored scripts due to flag.
[         script:yarn] [yarn]	Done in 12.11s.
[ citizen-server-impl] Build tasks completed - starting resource screenshot-basic.
[    c-scripting-core] Creating script environments for npwd
[ citizen-server-impl] Started resource npwd
[ citizen-server-impl] Started resource screenshot-basic
[         script:yarn] [yarn]	[1/4] Resolving packages...
[ citizen-server-impl] server thread hitch warning: timer interval of 474 milliseconds
[         script:yarn] [yarn]	success Already up-to-date.
[         script:yarn] [yarn]	Done in 12.95s.
[ citizen-server-impl] Build tasks completed - starting resource screenshot-basic.
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [yarn]	[1/4] Resolving packages...
[         script:yarn] Error: [yarn]	warning Waiting for the other yarn instance to finish (pid undefined, inside undefined)
[         script:yarn] [yarn]	[2/4] Fetching packages...
[         script:yarn] [yarn]	[3/4] Linking dependencies...
[         script:yarn] [yarn]	[4/4] Building fresh packages...
[         script:yarn] Error: [yarn]	warning Ignored scripts due to flag.
[         script:yarn] [yarn]	Done in 1.64s.
[ citizen-server-impl] Build tasks completed - starting resource sessionmanager-rdr3.
[           resources] Warning: Resource sessionmanager-rdr3 does not support the current game (gta5).
[         script:yarn] [yarn]	[1/4] Resolving packages...
[         script:yarn] [yarn]	success Already up-to-date.
[         script:yarn] [yarn]	Done in 1.80s.
[ citizen-server-impl] Build tasks completed - starting resource sessionmanager-rdr3.
[           resources] Warning: Resource sessionmanager-rdr3 does not support the current game (gta5).
[ script:renzu_tuners] SCRIPT ERROR: @renzu_tuners/server/sql.lua:90: renzu_tuners was unable to execute a query!
[ script:renzu_tuners] Table 'zap653262-1.player_vehicles' doesn't exist
[ script:renzu_tuners] SELECT plate FROM `player_vehicles` []
[ script:renzu_tuners] > saveall (@renzu_tuners/server/sql.lua:90)
[ script:renzu_tuners] > fn (@renzu_tuners/server/main.lua:128)
[ script:renzu_tuners] > <unknown> (@oxmysql/dist/build.js:21832)
[ script:renzu_tuners] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:hardcap] Connecting: Protschko
[      script:hardcap] Connecting: Da_Elio
[         script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[         script:npwd] > <unknown> (@npwd/resources/dist/server/server.js:48643)
[         script:npwd] 
[         script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[         script:npwd] > <unknown> (@npwd/resources/dist/server/server.js:48643)
[         script:npwd] 
[         script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[         script:npwd] > <unknown> (@npwd/resources/dist/server/server.js:48643)
[         script:npwd] 
[         script:npwd] SCRIPT ERROR in event `npwd:getCredentials': TypeError: Cannot read properties of null (reading 'getPhoneNumber')
[         script:npwd] > <unknown> (@npwd/resources/dist/server/server.js:48643)
[         script:npwd] 
[         script:chat] Protschko: t
> txaReportResources
[      script:monitor] [txAdminClient] Sending resources list to txAdmin.

**Comment by Achim-Sommer** [comment]
[ c-resources-core] Resource 'es_extended' can't run:
[ c-resources-core] 1. native(0x6AE51D4B): native 0x6AE51D4B isn't supported

Kein Fehler vom Template Server. (Veraltet Server Version)
